MageSMelee
constexpr int MageSMelee::NUM_TILES
Referenced by handleClick.
TileCoords MageSMelee::BACK_BTN
Referenced by handleClick.
TileCoords MageSMelee::TILE_COORDS[NUM_TILES]
Referenced by handleClick, render.
int MageSMelee::indexCliked
Referenced by handleClick, MageSMelee.
GameEngine* MageSMelee::engine
Referenced by handleClick, MageSMelee, PlayVAi::PlayVAi, PlayVPetiGran::PlayVPetiGran, render, PlayVAi::render, PlayVPetiGran::render, undo.
SDL_Surface* MageSMelee::backgroundSuface
Referenced by MageSMelee, render, ~MageSMelee.
SDL_Surface* MageSMelee::window_surface
SDL_Surface* MageSMelee::tileSurface
SDL_Surface* MageSMelee::oSprite
Referenced by MageSMelee, render, ~MageSMelee.
SDL_Surface* MageSMelee::xSprite
Referenced by MageSMelee, render, ~MageSMelee.
std::array<std::array<Tile, 5>, 5> MageSMelee::board
Referenced by handleClick, render, undo.
Uint32 MageSMelee::frameStart
Referenced by MageSMelee, render.
int MageSMelee::frameCount
Referenced by MageSMelee, render.
int MageSMelee::fps
Referenced by MageSMelee, render.
MageSMelee::MageSMelee(SDL_Window *win)
References backgroundSuface, engine, fps, frameCount, frameStart, View::getWorkingDirectory, indexCliked, oSprite, View::windowSurface, xSprite.
MageSMelee::~MageSMelee()
References backgroundSuface, oSprite, xSprite.
void MageSMelee::render() override
References backgroundSuface, Tile::Blank, board, TileCoords::bottomLeft, engine, fps, frameCount, frameStart, Player::getName, GameEngine::getWichSignPlay, GameEngine::getWinner, GameEngine::isWinner, Tile::O, oSprite, View::renderText, TILE_COORDS, TileCoords::topLeft, TileCoords::topRight, View::windowSurface, Tile::X, xSprite.
Referenced by PlayVAi::render, PlayVPetiGran::render.
bool MageSMelee::hasUndo() override
void MageSMelee::undo() override
References board, engine, GameEngine::getBoard, GameEngine::undoMove.
bool MageSMelee::isPointInTile(const SDL_Point &point, const TileCoords &tile)
References TileCoords::bottomLeft, TileCoords::topLeft, TileCoords::topRight.
Referenced by handleClick.
View * MageSMelee::handleClick(int, int) override
References BACK_BTN, board, engine, GameEngine::getBoard, GameEngine::getCoordsFromIndex, View::getWorkingDirectory, indexCliked, isPointInTile, GameEngine::move, NUM_TILES, GameEngine::printBoard, TILE_COORDS, View::window.