GameEngine
std::vector<GameBoardMemento> GameEngine::history
GameBoard* GameEngine::board
Player& GameEngine::playerOne
Player& GameEngine::playerTwo
Tile::Sign GameEngine::whichPlay
GameEngine::GameEngine(Player &playerOne, Player &playerTwo)
References GameBoard::saveToMemento, Tile::X.
bool GameEngine::move(const int x, const int y, const int new_x, const int new_y)
References GameBoard::move, GameBoard::saveToMemento.
Referenced by MageSMelee::handleClick, makeIAmove, move.
bool GameEngine::move(const int index, const int new_x, const int new_y)
References getCoordsFromIndex, move.
void GameEngine::printBoard()
References GameBoard::printBoard.
Referenced by MageSMelee::handleClick, makeIAmove, undoMove.
void GameEngine::makeIAmove()
References PlayerAI::getPlay, makeIAmove, move, printBoard.
Referenced by makeIAmove.
bool GameEngine::isWinner()
References GameBoard::getBoard.
Referenced by getWinner, MageSMelee::render, PlayVAi::render, PlayVPetiGran::render.
Tile::Sign GameEngine::getWichSignPlay()
Referenced by MageSMelee::render, PlayVAi::render, PlayVPetiGran::render.
std::array< std::array< Tile, 5 >, 5 > GameEngine::getBoard()
References GameBoard::getBoard.
Referenced by MageSMelee::handleClick, MageSMelee::undo.
std::vector< std::pair< int, int > > GameEngine::getPlayableFrom(int x, int y)
std::pair< int, int > GameEngine::getCoordsFromIndex(int index)
Referenced by MageSMelee::handleClick, move.
int GameEngine::getIndexFromCoords(const int x, const int y)
Player GameEngine::getWinner()
References isWinner, Tile::X.
Referenced by MageSMelee::render.
void GameEngine::undoMove()
References Tile::O, printBoard, GameBoard::restoreFromMemento, undoMove.
Referenced by MageSMelee::undo, undoMove.
bool GameEngine::isRowWin(int row)
bool GameEngine::isColumnWin(int column)
bool GameEngine::isMainDiagonalWin()
bool GameEngine::isAntiDiagonalWin()
void GameEngine::toogleWichPlay()
bool GameEngine::isValidMove(const int x, const int y, const int new_x, const int new_y)
Know if a move is legal or not.
x y new_x new_y true if the move is legal false if the move isn't legal