GameBoard
std::array<std::array<Tile, 5>, 5> GameBoard::board
GameBoard::GameBoard()
Construct a new Game Board object. Initializes the game board by filling it with blank tiles.
bool GameBoard::move(const int x, const int y, const int new_x, const int new_y, const Tile::Sign sign)
Executes a move on the game board. Checks if the move is valid and then applies it by updating the tiles on the board.
x The x-coordinate of the starting position. y The y-coordinate of the starting position. new_x The x-coordinate of the ending position. new_y The y-coordinate of the ending position. sign The player's sign (X or O). true if the move is valid and successfully made, false otherwise.
Referenced by MinMaxAI::getPlay, GameEngine::move, move.
bool GameBoard::move(const std::vector< int > &, const Tile::Sign sign)
Executes a move on the game board. Validates and applies the move described in the vector to the board.
inMove The move to be made, represented as a vector {x, y, new_x, new_y}. sign The player's sign (X or O). true if the move is valid and successfully made, false otherwise.
References move.
void GameBoard::printBoard()
Prints the current state of the game board. Iterates through the board and prints 'X', 'O', or 'B' representing the state of each tile. Usefull for debugging.
References Tile::O, Tile::X.
Referenced by GameEngine::printBoard.
std::array< std::array< Tile, 5 >, 5 > GameBoard::getBoard()
Gets the current state of the game board. Returns a copy of the 2D array representing the game board.
std::array<std::array<Tile, 5>, 5> The current state of the game board.
Referenced by GameEngine::getBoard, GameEngine::isWinner.
std::vector< std::vector< int > > GameBoard::getPossibleMoves(const Tile::Sign currentPlayer)
Calculates all possible moves for the current player. Analyzes the game board and returns a list of valid moves for the given player.
currentPlayer The current player's sign (X or O). std::vector<std::vector<int>> List of possible moves, each move is represented as a vector {x, y, new_x, new_y}.
References Tile::Blank.
Referenced by MinMaxAI::getPlay.
GameBoardMemento GameBoard::saveToMemento()
Referenced by GameEngine::GameEngine, GameEngine::move.
void GameBoard::restoreFromMemento(const GameBoardMemento memento)
References GameBoardMemento::getState.
Referenced by GameEngine::undoMove.
bool GameBoard::isValidMove(const int x, const int y, const int new_x, const int new_y, const Tile::Sign sign)
Validates a proposed move. Checks if the move is legal according to the game rules (e.g., starting from an edge tile, moving in the same row or column).
x The x-coordinate of the starting position. y The y-coordinate of the starting position. new_x The x-coordinate of the ending position. new_y The y-coordinate of the ending position. sign The player's sign (X or O). true if the move is valid, false otherwise.