View
SDL_Window* View::window
Referenced by display, MageSMelee::handleClick, View.
SDL_Surface* View::windowSurface
Referenced by clear, MageSMelee::MageSMelee, MainMenu::MainMenu, Loading::render, MageSMelee::render, MainMenu::render, renderCenteredText, renderText, View.
void View::renderText(const std::string &text, int x, int y, SDL_Color color, int size)
Renders text on the window surface at specified coordinates. Uses SDL_ttf to create a surface from the provided text and blits it onto the window surface. Displays an error if the font fails to load or text surface cannot be rendered.
text The string to be rendered. x The x-coordinate where the text will be rendered. y The y-coordinate where the text will be rendered. color The color of the text. size The font size for the text.
References getWorkingDirectory, windowSurface.
Referenced by MageSMelee::render, MainMenu::render.
bool View::isPointInPoly(int x, int y, const std::vector< std::pair< int, int > > &poly)
Know if point is in the polygon. This method use Ray-casting algorythm. More here: https://rosettacode.org/wiki/Ray-casting_algorithm.
x Point Coord y Point Coord poly All point that define your polygone true If the point is inside false If the point is outside
Referenced by MainMenu::render.
void View::renderCenteredText(const std::string &text, int winWidth, int startY, SDL_Color color, int fontSize)
Renders text centered horizontally on the window surface. Similar to renderText but aligns the text in the center of the window. The x-coordinate is calculated based on the window width and text dimensions.
text The string to be rendered. winWidth Width of the window for centering the text. startY The starting y-coordinate for the text. color The color of the text. fontSize The size of the font.
References getWorkingDirectory, windowSurface.
Mix_Chunk * View::loadAudio(std::string filename, int level)
Loads an audio file. Loads a WAV audio file from the specified path and sets its volume level. Displays an error if the audio file cannot be loaded.
filename The name of the audio file to load. level The volume level for the audio. Mix_Chunk* Pointer to the loaded audio chunk, or NULL if loading fails.
References getWorkingDirectory.
Referenced by playAudio, PlayVAi::PlayVAi, PlayVPetiGran::PlayVPetiGran, MainMenu::render, PlayVAi::render, PlayVPetiGran::render.
void View::playAudio(std::string filename, int level, int canal)
Loads and plays an audio file on a specific channel. A convenience method that combines loading and playing of an audio file.
filename The name of the audio file to load and play. level The volume level for the audio. canal The audio channel on which to play the audio.
References loadAudio.
Referenced by PlayVAi::PlayVAi, PlayVPetiGran::PlayVPetiGran, MainMenu::render, PlayVAi::render, PlayVPetiGran::render.
void View::playAudio(Mix_Chunk *gAudio, int canal)
Plays an audio chunk on a specific audio channel. Uses SDL_mixer to play the provided audio chunk.
gAudio Pointer to the Mix_Chunk audio chunk to be played. canal The audio channel on which to play the audio.
std::string View::getWorkingDirectory()
Retrieves the current working directory. Returns a string representing the absolute path of the current working directory.
std::string The current working directory path.
References GETCWD.
Referenced by MageSMelee::handleClick, loadAudio, MageSMelee::MageSMelee, MainMenu::MainMenu, MainMenu::render, renderCenteredText, renderText.
View::View(SDL_Window *win)
Construct a new View object. Initializes the windowSurface by getting the surface from the provided SDL_Window. Displays an error message if the window surface cannot be obtained.
win Pointer to SDL_Window to be used for rendering.
References window, windowSurface.
View::~View()
Destructor for the View object. Cleans up resources when the View object is destroyed.
virtual void View::undo()=0
Referenced by Controller::handleEvents.
virtual View * View::handleClick(int, int)=0
Referenced by Controller::handleEvents.
virtual bool View::hasUndo()=0
Referenced by Controller::handleEvents.
virtual void View::render()=0
Referenced by Controller::run.
void View::clear()
Clears the window surface. Fills the window surface with black color (RGB 0, 0, 0).
References windowSurface.
void View::display()
Updates the window surface. Displays the current contents of the window surface on the screen.
References window.