Controller
Controller * Controller::instance
Singleton instance of the Controller class. Used to ensure that only one instance of the Controller class exists throughout the application.
View* Controller::view
SDL_Window* Controller::window
Mix_Chunk* Controller::gMusic
bool Controller::isRunning
int Controller::mouseX
int Controller::mouseY
Controller::Controller()
Construct a new Controller object. Initializes SDL, SDL_ttf, and SDL_mixer. Creates the main window and loads initial audio resources. Exits the application with an error message if initialization fails or resources cannot be loaded.
void Controller::updateView(View *newView)
Updates the current view. Clears the current window surface, deletes the old view, and replaces it with a new view. This method is typically called in response to user interactions.
newView Pointer to the new view that will replace the current view.
Controller::Controller(const Controller &)=delete
Controller & Controller::operator=(const Controller &)=delete
Controller::~Controller()
Destructor for the Controller object. Cleans up resources, frees loaded audio chunks, destroys the window, and quits SDL.
void Controller::run()
Main loop of the application. Manages the application flow, starting with the Loading screen, then moving to the MainMenu. Handles events and updates the window surface continuously until the application is closed.
References handleEvents, View::render.
Referenced by main.
void Controller::handleEvents()
Handles user input and system events. Processes all SDL events, such as quitting the application, mouse button presses, and keydown events. Updates the view based on user interactions or system commands.
References View::handleClick, View::hasUndo, View::undo.
Referenced by run.
static Controller * Controller::getInstance()
Referenced by main.